# Generated by Django 3.2.5 on 2021-07-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0002_rename_user_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='keep.label'),
        ),
    ]
