# Generated by Django 3.2.5 on 2021-07-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0003_alter_note_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
    ]
