# Generated by Django 3.2.5 on 2021-07-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0004_remove_note_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='label',
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(null=True, related_name='notes', to='keep.Label'),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
