# Generated by Django 3.2.5 on 2021-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0005_auto_20210724_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(related_name='notes', to='keep.Label'),
        ),
    ]
