# Generated by Django 3.2.5 on 2021-07-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0006_alter_note_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='label',
            new_name='labels',
        ),
    ]
